server:
  port: 10086
spring:
  application:
#    服务名称
    name: eurekaserver
eureka:
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: false # 是否拉取其它服务的信息，默认是true
    service-url:
#      注册中心的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
